export interface VerseReference {
  surah: number;
  ayah: number;
  surahName: string;
}

export const QURAN_WORD_VERSES: VerseReference[] = [
  { surah: 2, ayah: 185, surahName: "Al-Baqarah" },
  { surah: 4, ayah: 82, surahName: "An-Nisa" },
  { surah: 5, ayah: 101, surahName: "Al-Ma'idah" },
  { surah: 7, ayah: 204, surahName: "Al-A'raf" },
  { surah: 9, ayah: 111, surahName: "At-Tawbah" },
  { surah: 10, ayah: 37, surahName: "Yunus" },
  { surah: 10, ayah: 61, surahName: "Yunus" },
  { surah: 12, ayah: 2, surahName: "Yusuf" },
  { surah: 12, ayah: 3, surahName: "Yusuf" },
  { surah: 13, ayah: 31, surahName: "Ar-Ra'd" },
  { surah: 15, ayah: 1, surahName: "Al-Hijr" },
  { surah: 15, ayah: 87, surahName: "Al-Hijr" },
  { surah: 15, ayah: 91, surahName: "Al-Hijr" },
  { surah: 16, ayah: 98, surahName: "An-Nahl" },
  { surah: 17, ayah: 9, surahName: "Al-Isra" },
  { surah: 17, ayah: 41, surahName: "Al-Isra" },
  { surah: 17, ayah: 45, surahName: "Al-Isra" },
  { surah: 17, ayah: 46, surahName: "Al-Isra" },
  { surah: 17, ayah: 60, surahName: "Al-Isra" },
  { surah: 17, ayah: 78, surahName: "Al-Isra" },
  { surah: 17, ayah: 82, surahName: "Al-Isra" },
  { surah: 17, ayah: 88, surahName: "Al-Isra" },
  { surah: 17, ayah: 89, surahName: "Al-Isra" },
  { surah: 17, ayah: 106, surahName: "Al-Isra" },
  { surah: 18, ayah: 54, surahName: "Al-Kahf" },
  { surah: 20, ayah: 2, surahName: "Taha" },
  { surah: 20, ayah: 113, surahName: "Taha" },
  { surah: 25, ayah: 30, surahName: "Al-Furqan" },
  { surah: 25, ayah: 32, surahName: "Al-Furqan" },
  { surah: 27, ayah: 1, surahName: "An-Naml" },
  { surah: 27, ayah: 6, surahName: "An-Naml" },
  { surah: 27, ayah: 76, surahName: "An-Naml" },
  { surah: 27, ayah: 92, surahName: "An-Naml" },
  { surah: 28, ayah: 85, surahName: "Al-Qasas" },
  { surah: 30, ayah: 58, surahName: "Ar-Rum" },
  { surah: 34, ayah: 31, surahName: "Saba" },
  { surah: 36, ayah: 2, surahName: "Ya-Sin" },
  { surah: 36, ayah: 69, surahName: "Ya-Sin" },
  { surah: 38, ayah: 1, surahName: "Sad" },
  { surah: 39, ayah: 27, surahName: "Az-Zumar" },
  { surah: 39, ayah: 28, surahName: "Az-Zumar" },
  { surah: 41, ayah: 3, surahName: "Fussilat" },
  { surah: 41, ayah: 26, surahName: "Fussilat" },
  { surah: 41, ayah: 44, surahName: "Fussilat" },
  { surah: 43, ayah: 3, surahName: "Az-Zukhruf" },
  { surah: 43, ayah: 31, surahName: "Az-Zukhruf" },
  { surah: 46, ayah: 29, surahName: "Al-Ahqaf" },
  { surah: 47, ayah: 24, surahName: "Muhammad" },
  { surah: 50, ayah: 1, surahName: "Qaf" },
  { surah: 50, ayah: 45, surahName: "Qaf" },
  { surah: 54, ayah: 17, surahName: "Al-Qamar" },
  { surah: 54, ayah: 22, surahName: "Al-Qamar" },
  { surah: 54, ayah: 32, surahName: "Al-Qamar" },
  { surah: 54, ayah: 40, surahName: "Al-Qamar" },
  { surah: 55, ayah: 2, surahName: "Ar-Rahman" },
  { surah: 56, ayah: 77, surahName: "Al-Waqi'ah" },
  { surah: 59, ayah: 21, surahName: "Al-Hashr" },
  { surah: 72, ayah: 1, surahName: "Al-Jinn" },
  { surah: 73, ayah: 4, surahName: "Al-Muzzammil" },
  { surah: 73, ayah: 20, surahName: "Al-Muzzammil" },
  { surah: 75, ayah: 17, surahName: "Al-Qiyamah" },
  { surah: 75, ayah: 18, surahName: "Al-Qiyamah" },
  { surah: 76, ayah: 23, surahName: "Al-Insan" },
  { surah: 84, ayah: 21, surahName: "Al-Inshiqaq" },
  { surah: 85, ayah: 21, surahName: "Al-Buruj" },
];
